# https://taskfile.dev

version: '3'

vars:
  GOMOD: github.com/smukherj1/k8s-signer

tasks:
  deploy:
    deps: [frontend-container]
    cmds:
      - kubectl apply -f k8s/frontend.yml
  frontend-container:
    deps: [frontend]
    cmds:
      - podman build -f containers/Containerfile.frontend -t {{.GOMOD}}/frontend:latest .
      - podman image save --format oci-archive {{.GOMOD}}/frontend:latest | sudo k3s ctr images import -
  frontend:
    deps: ["signer-proto"]
    cmds:
      - go build -o out/frontend {{.GOMOD}}/bin/frontend
    sources:
      - "**/*.go"
    generates:
      - out/frontend
  signer-proto:
    cmds:
      - |
        protoc --proto_path=protos \
          --go_out=generated --go_opt=paths=import \
          --go-grpc_out=generated --go-grpc_opt=paths=import \
          --grpc-gateway_out=generated --grpc-gateway_opt=paths=import \
          protos/signer.proto
    sources:
      - protos/*.proto
      - protos/**/*.proto
    generates:
      - generated/**/*.go
