apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: signer
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: signer
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: github.com/smukherj1/k8s-signer/frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 256M