apiVersion: v1
kind: Service
metadata:
  name: signer-frontend
  namespace: signer
spec:
  type: LoadBalancer
  selector:
    app: signer-frontend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signer-frontend
  namespace: signer
  labels:
    app: signer-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signer-frontend
  template:
    metadata:
      labels:
        app: signer-frontend
    spec:
      containers:
      - name: signer-frontend
        image: github.com/smukherj1/k8s-signer/signer-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 256M