apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: signer
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: github.com/smukherj1/k8s-signer/worker:latest
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 500m
            memory: 256M